apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: pool
  template:
    metadata:
      labels:
        app: pool
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: pool
        image: pollacr999.azurecr.io/poll_app:latest
        ports:
        - containerPort: 8000
        env:
        - name: APPNAME
          value: "pool"
        - name: db_host
          valueFrom:
            secretKeyRef:
              name: akvsecretscertwin
              key: DB_HOST
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: akvsecretscertwin
              key: DB_USER
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: akvsecretscertwin
              key: DB_PASSWORD
        - name: db_port
          valueFrom:
            secretKeyRef:
              name: akvsecretscertwin
              key: DB_PORT
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: akvsecretscertwin
              key: DB_NAME
        volumeMounts:
          - mountPath: "/mnt/azure"
            name: volume
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        imagePullPolicy: Always
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-win"
        - name: volume
          persistentVolumeClaim:
            claimName: poll-azurefile-share
  
---
apiVersion: v1
kind: Service
metadata:
  name: pool
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: pool